### ISSUE TITLE
WeChatOcr程序中添加 Task.Run后线程就跑飞了，不返回结果

### ISSUE THREAD

**Issue by taijifeng** [ZGGSONG/WeChatOcr#3]
private void Ocr_Click(object sender, RoutedEventArgs e)
{
    var ocrsult = string.Empty;

    Task.Run(() =>
    {
        if (_bitmap == null)
        {
            ocrsult = "Please capture the screen first.";
            return;
        }
        var bitmap = (Bitmap)_bitmap.Clone();

        if (_tcs is { Task.IsCompleted: false })
        {
            ocrsult = "Please wait for the previous OCR operation to complete.";
            return;
        }
        _tcs = new TaskCompletionSource<string>();

我在写代码过程中发现只要将OCR的代码包含在task.run里面之后，整个代码就跑飞了，不返回结果，也无法捕获异常，我最开始是看了stranslate这个项目才看到你这个项目的，测试发现两个项目都存在这个问题，由于个人能力有限，还无法找到问题在哪，希望看到问题帮忙解决下，非常感谢！

**Comment by ZGGSONG** [comment]
```cs
private async void Ocr_Click
```

```cs
await Task.Run(() =>
```

**Comment by taijifeng** [comment]
> ```cs
> private async void Ocr_Click
> ```
> 
> ```cs
> await Task.Run(() =>
> ```

非常感谢这么快回复，经过你提示之后，我反复修改对比了代码，发现如果这样的话就可以了：
        var completedTask = Task.WhenAny(_tcs.Task, timeoutTask);

        if (completedTask == timeoutTask) throw new TimeoutException("WeChatOCR operation timed out.");
        // 提取content的值
        var finalResult = _tcs.Task;
而stranslate中的写法是：(这种写法会卡死task 线程，不返回结果)
        var completedTask = await Task.WhenAny(tcs.Task, timeoutTask);

        if (completedTask == timeoutTask) throw new TimeoutException("WeChatOCR operation timed out.");
        // 提取content的值
        var finalResult = await tcs.Task;
最终调用使用：        
        ResultTb.Text = await Task.Run(() =>
        {
            // 模拟耗时计算
            return ExecuteAsync(text, CancellationToken.None);
        });

主要区别在于两个await的使用，还望指教下为什么会有这种情况，谢谢

**Comment by taijifeng** [comment]
参考链接：https://www.cnblogs.com/cdaniu/p/15869866.html
创建TaskCompletionSource时建议使用TaskCreationOptions.RunContinuationsAsynchronously属性，

对于编写类库的人来说TaskCompletionSource<T>是一个具有非常重要的作用,默认情况下任务延续可能会在调用try/set(Result/Exception/Cancel)的线程上进行运行,这也就是说作为编写类库的人来说必须需要考虑上下文,这通常是非常危险,可能就会导致死锁' 线程池饥饿 *数据结构损坏(如果代码异常运行)

所以在创建TaskCompletionSourece<T>时,应该使用TaskCreationOption.RunContinuationAsyncchronously参数将后续任务交给线程池进行处理
